/*
 * Generated by mach9 add_arm64.o; DO NOT EDIT.
 */

#include "textflag.h"

TEXT ·armadd(SB),NOSPLIT,$0-24
	WORD $0xf9400ba0 // ldr x0, [x29, #16]
	WORD $0xf9400fa1 // ldr x1, [x29, #24]
	WORD $0x8b010000 // add x0, x0, x1
	WORD $0xf90013a0 // str x0, [x29, #32]
	WORD $0xd65f03c0 // ret

